version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "rxkeeporder/build.gradle" }}-{{ checksum  "rxkeeporder-sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "rxkeeporder/build.gradle" }}-{{ checksum  "rxkeeporder-sample/build.gradle" }}
      - run:
          name: execute test
          command: ./gradlew test
